[config]

[config.wallpaper]
set = true
command = ""
pre_hook = "$HOME/.config/hypr/scripts/make-static-wallpaper.sh $($HOME/.config/hypr/scripts/get-current-swww-wallpaper.sh)"


[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.swaync]
input_path = './templates/swaync-colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.wlogout]
input_path = './templates/waybar.css'
output_path = '~/.config/wlogout/matugen-colors.css'

# [templates.obsidian]
# input_path = './templates/obsidian-matugen-colors.css'
# output_path = './output/obsidian-minimal-colors.css'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
