[config]

[config.wallpaper]
set = true
command = ""
pre_hook = "$HOME/.config/hypr/scripts/make-static-wallpaper.sh $($HOME/.config/hypr/scripts/get-current-swww-wallpaper.sh)"


[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.ghostty]
input_path = './templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.swaync]
input_path = './templates/swaync-colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
